name: "CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: c-hive/gha-yarn-cache@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - name: "Install dependencies"
        run: yarn install --frozen-lockfile

      - name: "Lint"
        run: yarn lint -f @jamesacarr/github-actions

  dependabot-merge:
    name: "Dependabot automerge"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    needs: [ "lint" ]
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  semantic-release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: [ "lint" ]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    outputs:
      new-release-published: ${{ steps.release.outputs.new-release-published }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          ref: "master"

      - uses: c-hive/gha-yarn-cache@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - name: "Install dependencies"
        run: yarn install --frozen-lockfile

      - name: "Release"
        id: "release"
        uses: codfish/semantic-release-action@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
